# Generated by Django 6.0.4 on 2026-05-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_factura_impuesto_alter_factura_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_factura',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturada', 'Facturada')], default='Pendiente', max_length=20),
        ),
    ]
