# Generated by Django 6.0.4 on 2026-05-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_restaurante_rol_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='horario',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='correo',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_reporte', models.CharField(choices=[('Ventas', 'Ventas'), ('Órdenes', 'Órdenes'), ('Clientes', 'Clientes'), ('Facturación', 'Facturación'), ('General', 'General')], max_length=30)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('total_ordenes', models.IntegerField(default=0)),
                ('total_clientes', models.IntegerField(default=0)),
                ('total_facturas', models.IntegerField(default=0)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado')),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
    ]
